import os
import inspect
from github import Github

# Creates github repo
def create_repo(name):
  # print "Connecting to API"
  g = Github(os.environ.get("GITHUB_API_USER"), os.environ.get("GITHUB_API_TOKEN"))
  org = g.get_organization(os.environ.get("GITHUB_ORGANIZATION"))
  # print "Creating GitHub repository..."
  repo = org.create_repo(name, private=True, auto_init=True, description="Automatically generated by project-bootstrap.")

  # print "Adding repository to devops team..."
  team = org.get_team(int(os.environ.get("GITHUB_TEAM")))
  team.add_to_repos(repo)

  return """Github Repository Information:
* Github URL:     """+repo.html_url+"""
* HTTP Clone URL: """+repo.clone_url+"""
* SSH Clone URL:  """+repo.ssh_url
